// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fA1TzWTCVWuH4wZ7vAuVV1M3dHB_1Mk',
    appId: '1:962980506136:web:750662aafa228c6d78316d',
    messagingSenderId: '962980506136',
    projectId: 'tpmusau-auth',
    authDomain: 'tpmusau-auth.firebaseapp.com',
    storageBucket: 'tpmusau-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWkNsybdSR6gRtzhDj1aypUt9z1JhvBpo',
    appId: '1:962980506136:android:8be51efb7700c34278316d',
    messagingSenderId: '962980506136',
    projectId: 'tpmusau-auth',
    storageBucket: 'tpmusau-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlk2AYIK-9rASMZtAnLqP6ILC9bR6z2RQ',
    appId: '1:962980506136:ios:f7c264d2c9ac170478316d',
    messagingSenderId: '962980506136',
    projectId: 'tpmusau-auth',
    storageBucket: 'tpmusau-auth.firebasestorage.app',
    iosBundleId: 'com.example.tpmusauAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlk2AYIK-9rASMZtAnLqP6ILC9bR6z2RQ',
    appId: '1:962980506136:ios:f7c264d2c9ac170478316d',
    messagingSenderId: '962980506136',
    projectId: 'tpmusau-auth',
    storageBucket: 'tpmusau-auth.firebasestorage.app',
    iosBundleId: 'com.example.tpmusauAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8fA1TzWTCVWuH4wZ7vAuVV1M3dHB_1Mk',
    appId: '1:962980506136:web:9a1300b8573d73ee78316d',
    messagingSenderId: '962980506136',
    projectId: 'tpmusau-auth',
    authDomain: 'tpmusau-auth.firebaseapp.com',
    storageBucket: 'tpmusau-auth.firebasestorage.app',
  );
}
